# Generated by Django 5.0.7 on 2024-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birht_data', models.DateField()),
                ('nationality', models.CharField(max_length=40)),
                ('disponibility', models.BooleanField(default=False)),
            ],
        ),
    ]
