# Generated by Django 5.0.7 on 2024-07-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birht_data',
            new_name='birth_data',
        ),
    ]
