# Generated by Django 5.0.7 on 2024-07-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_birht_data_author_birth_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
